/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"


void
mathprog_1( char* host)
{
	CLIENT *clnt;
	result  *result_1;
	numbers  mathplus_1_arg = { 1, 1};
	result  *result_2;
	numbers  mathminus_1_arg = { 1, 2};
	result  *result_3;
	numbers  mathtimes_1_arg = { 3, 9};
	result  *result_4;
	numbers  mathdiv_1_arg = { 3, 2};

	clnt = clnt_create(host, MATHPROG, MATHVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	result_1 = mathplus_1(&mathplus_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}

	printf("Soma de %f e %f: %f\n", mathplus_1_arg.a, mathplus_1_arg.b, *result_1);

	result_2 = mathminus_1(&mathminus_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}

	printf("Subtracao de %f e %f: %f\n",mathminus_1_arg.a, mathminus_1_arg.b, *result_2);

	result_3 = mathtimes_1(&mathtimes_1_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}

	printf("Multiplicacao de %f e %f: %f\n", mathtimes_1_arg.a, mathtimes_1_arg.b, *result_3);

	result_4 = mathdiv_1(&mathdiv_1_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}

	printf("Divisao de %f por %f: %f\n", mathdiv_1_arg.a, mathdiv_1_arg.b, *result_4);

	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 1) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	mathprog_1( host );
}
