/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"

result * mathplus_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static result  result;

	result = argp->a + argp->b;

	return(&result);
}

result * mathminus_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static result  result;

	result = argp->a - argp->b;

	return(&result);
}

result * mathtimes_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static result  result;

	result = argp->a * argp->b;

	return(&result);
}

result * mathdiv_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static result  result;

	if ( argp->b != 0 )
		result = argp->a / argp->b;

	return(&result);
}
