/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATH_H_RPCGEN
#define _MATH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float a;
	float b;
};
typedef struct numbers numbers;

typedef float result;

#define MATHPROG 0x31253100
#define MATHVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MATHPLUS 1
extern  result * mathplus_1(numbers *, CLIENT *);
extern  result * mathplus_1_svc(numbers *, struct svc_req *);
#define MATHMINUS 2
extern  result * mathminus_1(numbers *, CLIENT *);
extern  result * mathminus_1_svc(numbers *, struct svc_req *);
#define MATHTIMES 3
extern  result * mathtimes_1(numbers *, CLIENT *);
extern  result * mathtimes_1_svc(numbers *, struct svc_req *);
#define MATHDIV 4
extern  result * mathdiv_1(numbers *, CLIENT *);
extern  result * mathdiv_1_svc(numbers *, struct svc_req *);
extern int mathprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MATHPLUS 1
extern  result * mathplus_1();
extern  result * mathplus_1_svc();
#define MATHMINUS 2
extern  result * mathminus_1();
extern  result * mathminus_1_svc();
#define MATHTIMES 3
extern  result * mathtimes_1();
extern  result * mathtimes_1_svc();
#define MATHDIV 4
extern  result * mathdiv_1();
extern  result * mathdiv_1_svc();
extern int mathprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATH_H_RPCGEN */
